name: Build and Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make a new .env file to back-end
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end
          file_name: .env
          fail_on_empty: true

      - name: Make a new .env file to front-end
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_APP_BACKEND_URL: ${{secrets.VITE_APP_BACKEND_URL}}
          directory: front-end
          file_name: .env
          fail_on_empty: true

      - name: Run docker compose down
        run: docker compose down

      - name: Delete react docker volume
        run: docker volume rm passwordgenerator_react-volume

      - name: Build docker images
        run: docker compose build

      - name: Run docker compose
        run: docker compose up -d
